### ISSUE TITLE
Review

### ISSUE THREAD

**Issue by dcollioni** [leosul/login-app#1]
- As chamadas pra API do covid poderiam ser feitas diretamente do front-end
- As funções repository normalmente se dedicam a acessar dados no banco de dados
- Essa rota parece que não está sendo usada `router.use("/countries/:country", authenticator, countryRouter);`
- Analisando essa expressão do arquivo `MainFormContainer.jsx`:
```
const contentCountry = content['Countries'].filter(
    s => s.Country === this.state.countryName
)[0]
```
1. Pode substituir `content['Countries']` por `content.Countries`
2. Pode substituir a função `filter` pela função [`find`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/find) que já retorna o primeiro resultado encontrado

- Por convenção, propriedades de objetos seguem padrão camelCase, de preferência nao usar PascalCase nas propriedades dos objetos (herança do C# haha)

- Os componentes `Card` e `ChartBar` eu faria eles receberem os valores já desestruturados que vão ser exibidos, exemplo: `countryName`, `totalConfirmed`... Dessa forma, teu componente não fica dependente da estrutura do objeto `countryData` que ele está recebendo atualmente. É mais interessante que o componente seja fácil de usar, da forma como eles estão estruturados hoje, o componente pai que está criando o Card ou ChartBar tem que ler o código desses componentes pra entender quais propriedades o objeto `countryData` precisa ter. Deu pra entender?

**Comment by leosul** [comment]
Perfeito @dcollioni seguem as respostas:

- As chamadas da API poderiam ser feitas pelo axios direto pelo Reactjs, mas foi minha preferência centralizar tudo na minha API, para futuras novas funcionalidades.

- Removi os repositórios que consumiam a API do covid, agora fazem parte somente dos services.

- Por enquanto não, mas fará parte de novas funcionalidades.

- Ótima alteração, já substituí a expressão e mais alguns outros ajustes parecidos com este.

- Convenções ajustadas também.

- Ajustados por parâmetros, os componentes Card e ChartBar agora os valores desestruturados.
